// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rqtweknmixqhdqwbucup.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxdHdla25taXhxaGRxd2J1Y3VwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NjgyMDAsImV4cCI6MjA2NjM0NDIwMH0.Ub48ouhNTazRL28UV0W_LRkfsE50PHuOULDQfQuU98k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);